### ISSUE TITLE
Allow setting context of status

### ISSUE THREAD

**Issue by jquast** [jquast/ghstat#2]
https://developer.github.com/v3/repos/statuses/

> Statuses can include a context to indicate what service is providing that status. For example, you may have your continuous integration service push statuses with a context of ci, and a security audit tool push statuses with a context of security. You can then use the combined status endpoint to retrieve the whole status for a commit.

**Comment by kad** [comment]
implemented in #3

**Comment by jquast** [comment]
closed by https://github.com/jquast/ghstat/pull/3
